language: python

matrix:
    include:
        - os: linux
          python: 3.7
          dist: trusty
        - os: linux
          python: 3.7
          dist: percise
        - os: linux
          python: 3.7
          dist: xenial
        - os: osx
          python: 3.7

addons:
  apt:
    sources:
      - sourceline: "ppa:duggan/bats"
    packages:
      - bats
      - make
      - pipenv
      - gnupg
  homebrew:
    update: true
    packages:
      - bats-core
      - make
      - pipenv
      - gnupg

script:
  - make setup
  - make build
  - make install-bin
  - bats test
