language: python
matrix:
  include:
  - os: linux
    python: 3.7
  - os: linux
    python: 3.8
git:
  depth: false
services:
- docker
env:
- PIPENV_IGNORE_VIRTUALENVS=1 MTLS_SERVER_VERSION=v0.17.0 TMP_DIR=/home/travis/build/drGrove/mtls-cli/tmp
addons:
  apt:
    packages:
    - cmake
    - libnss3-tools
  artifacts:
    s3_region: "us-west-1"
    paths:
      - $(ls mtls-*.tar.gz | tr "\n" ":")

before_install:
- docker pull drgrove/mtls-server:${MTLS_SERVER_VERSION}
- pip3 install pipenv

install:
- make setup

script:
- make test coverage
- make pkg SIGN=0

after_success:
- make coveralls
