language: python
matrix:
  include:
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7-dev
  - os: osx
    language: generic
services:
- docker
env:
- PIPENV_IGNORE_VIRTUALENVS=1 MTLS_SERVER_VERSION=v0.16.3 TMPDIR=/home/travis/tmp
addons:
  apt:
    packages:
    - cmake
    - libnss3
  homebrew:
    packages:
    - nss
    - gnupg
    - openssl
    - python3
  artifacts:
    s3_region: "us-west-1"
    paths:
      - $(ls mtls-*.tar.gz | tr "\n" ":")

before_install:
- docker pull drgrove/mtls-server:${MTLS_SERVER_VERSION}
- pip3 install pipenv

install:
- make setup

script:
- make test coverage
- make pkg SIGN=0

after_success:
- make coveralls
