language: python

matrix:
    include:
        - os: linux
          python: 3.7
          dist: trusty
        - os: linux
          python: 3.7
          dist: percise
        - os: linux
          python: 3.7
          dist: xenial
        - os: osx
          python: 3.7
